language: php
before_script:
  - mysql -e 'create database testdb;'
  - mysql --user=travis --password="" --host=localhost --database=testdb < documents/restfor.sql
  - echo "server.domain=localhost" >> conf/conf.dat
  - echo "database.database=testdb" >> conf/conf.dat
  - echo "database.user=travis" >> conf/conf.dat
  - echo "database.password=" >> conf/conf.dat
  - echo "auth.type=basic" >> conf/conf.dat
  - echo "auth.source=conf" >> conf/conf.dat
  - echo "auth.public.id=0" >> conf/conf.dat
  - echo "auth.users.public.group=0" >> conf/conf.dat
  - echo "auth.users.public.rights.+.path=/(.*)" >> conf/conf.dat
  - echo "auth.users.public.rights.*.methods=OPTIONS,GET,PUT,POST,DELETE, PATCH" >> conf/conf.dat
  - echo "auth.users.webmaster.id=1" >> conf/conf.dat
  - echo "auth.users.webmaster.group=1" >> conf/conf.dat
script: env REQUEST_URI="/unit.dat?verbose=yes&multiple=yes" QUERY_STRING="verbose=yes&multiple=yes" REQUEST_METHOD="GET" HTTPS="on" php index.php
